Revert "(feat) Downloads in temporary dir"
This reverts commit 4f04e091afa2b9b7cebf2d5b775b17928189bcd6.

This is since downloading and then moving the files got the error

   OSError: [Errno 18] Cross-device link

So not using tmp